#pragma once

#define EE_HANDS
#define VIAL_KEYBOARD_UID {0x0c, 0x61, 0x2e, 0x63, 0x57, 0x9f, 0x50, 0x8d}
#define VIAL_TAP_DANCE_ENTRIES 8
#define VIAL_COMBO_ENTRIES 8
#define PICO_FLASH_SIZE_BYTES (1 * 1024 * 1024)
// #define MK_3_SPEED
// #define MK_MOMENTARY_ACCEL
#define MK_COMBINED
#define DYNAMIC_KEYMAP_LAYER_COUNT 8   // 例：8レイヤー

// config.h
#define MOUSEKEY_DELAY 0
#define MOUSEKEY_INTERVAL 16
#define MOUSEKEY_MOVE_DELTA 5
#define MOUSEKEY_MAX_SPEED 10
#define MOUSEKEY_TIME_TO_MAX 150

#define MK_C_OFFSET_0 1
#define MK_C_INTERVAL_0 32
#define MK_C_OFFSET_1 1
#define MK_C_INTERVAL_1 8
#define MK_C_OFFSET_2 1
#define MK_C_INTERVAL_2 1
